import { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import AuthContext from '../context/AuthContext';
import { Bot, Zap, MessageSquare, AlertTriangle } from 'lucide-react';
import { toast } from 'react-toastify';
import { Link } from 'react-router-dom';

const AiAnalysis = () => {
  const { user } = useContext(AuthContext);
  const [complaints, setComplaints] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAnalyzedComplaints = async () => {
      try {
        const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5000';
        const res = await axios.get(`${apiUrl}/api/complaints`, {
          headers: { Authorization: `Bearer ${user.token}` }
        });
        
        // Filter only complaints that have AI analysis
        const analyzed = res.data.filter(c => c.aiAnalysis);
        setComplaints(analyzed);
      } catch (error) {
        toast.error('Failed to fetch AI analytics');
      } finally {
        setLoading(false);
      }
    };

    if (user) {
      fetchAnalyzedComplaints();
    }
  }, [user]);

  const getPriorityColor = (priority) => {
    const p = (priority || '').toLowerCase();
    if (p.includes('critical')) return 'text-red-400 bg-red-400/10 border-red-400/20';
    if (p.includes('high')) return 'text-orange-400 bg-orange-400/10 border-orange-400/20';
    if (p.includes('medium')) return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/20';
    return 'text-blue-400 bg-blue-400/10 border-blue-400/20';
  };

  return (
    <div className="animate-fade-in max-w-5xl mx-auto">
      <div className="flex items-center gap-4 mb-8">
        <div className="p-3 bg-indigo-500/10 rounded-xl border border-indigo-500/20">
          <Bot size={32} className="text-indigo-400" />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-white mb-1">AI Analysis Dashboard</h1>
          <p className="text-slate-400">Deep insights and automated responses generated by our AI engine.</p>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-500"></div>
        </div>
      ) : complaints.length === 0 ? (
        <div className="glass-panel p-12 text-center rounded-2xl border border-slate-800">
          <Bot size={48} className="mx-auto text-slate-600 mb-4" />
          <h3 className="text-xl font-bold text-white mb-2">No AI Data Available</h3>
          <p className="text-slate-400 mb-6">Submit a new complaint to see the AI analysis in action.</p>
          <Link to="/complaints/new" className="inline-block bg-indigo-600 hover:bg-indigo-700 text-white font-medium px-6 py-3 rounded-lg transition-colors">
            Create Complaint
          </Link>
        </div>
      ) : (
        <div className="space-y-6">
          {complaints.map(complaint => (
            <div key={complaint._id} className="glass-panel p-6 rounded-2xl border border-slate-800 flex flex-col md:flex-row gap-6">
              
              {/* Left side: Original Complaint Info */}
              <div className="flex-1 border-r border-slate-800/0 md:border-slate-800 pr-0 md:pr-6">
                <h3 className="text-xl font-bold text-white mb-2">{complaint.title}</h3>
                <p className="text-slate-400 text-sm mb-4">{complaint.description}</p>
                <div className="text-xs text-slate-500 flex flex-col gap-1">
                  <span>Category: {complaint.category}</span>
                  <span>Location: {complaint.location}</span>
                </div>
              </div>
              
              {/* Right side: AI Insights */}
              <div className="flex-[1.5] space-y-4">
                <div className="flex items-center gap-2 mb-2">
                  <Zap size={18} className="text-indigo-400" />
                  <h4 className="font-bold text-indigo-300">AI Breakdown</h4>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-800">
                    <p className="text-xs text-slate-500 mb-1 font-medium uppercase tracking-wider">Priority Level</p>
                    <span className={`inline-block px-3 py-1 rounded border text-sm font-bold ${getPriorityColor(complaint.aiAnalysis.priority)}`}>
                      {complaint.aiAnalysis.priority || 'Unknown'}
                    </span>
                  </div>
                  <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-800">
                    <p className="text-xs text-slate-500 mb-1 font-medium uppercase tracking-wider">Department</p>
                    <span className="text-white font-medium">
                      {complaint.aiAnalysis.department || 'General Routing'}
                    </span>
                  </div>
                </div>

                <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-800">
                  <div className="flex items-start gap-3">
                    <AlertTriangle size={18} className="text-slate-500 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="text-xs text-slate-500 mb-1 font-medium uppercase tracking-wider">AI Summary</p>
                      <p className="text-sm text-slate-300">{complaint.aiAnalysis.summary}</p>
                    </div>
                  </div>
                </div>

                <div className="bg-indigo-900/10 p-4 rounded-xl border border-indigo-500/20">
                  <div className="flex items-start gap-3">
                    <MessageSquare size={18} className="text-indigo-400 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="text-xs text-indigo-300/70 mb-1 font-medium uppercase tracking-wider">Suggested Auto-Response</p>
                      <p className="text-sm text-indigo-100 italic">"{complaint.aiAnalysis.autoResponse}"</p>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default AiAnalysis;
